export const DashboardActions = {
  GET_DASHBOARD: "GET_DASHBOARD",
  GET_DASHBOARD_BY_ID: "GET_DASHBOARD_BY_ID",
  ADD_DASHBOARD: "ADD_DASHBOARD",
  UPDATE_DASHBOARD: "UPDATE_DASHBOARD",
  DELETE_DASHBOARD: "DELETE_DASHBOARD",
};
