const PolicyActions = {
  GET_POLICIES: "GET_POLICIES",
  GET_POLICY_BY_ID: "GET_POLICY_BY_ID",
  SET_POLICIES_LOADING: "SET_POLICIES_LOADING",
  ADD_POLICY: "ADD_POLICY",
  UPDATE_POLICY: "UPDATE_POLICY",
  DELETE_POLICY: "DELETE_POLICY",
};

export { PolicyActions };
